# Generated by Django 5.2.4 on 2025-07-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.AddField(
            model_name='review',
            name='text_el',
            field=models.TextField(blank=True, null=True, verbose_name='Text (Greek)'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_en',
            field=models.TextField(default='English placeholder', verbose_name='Text (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='text_es',
            field=models.TextField(blank=True, null=True, verbose_name='Text (Spanish)'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Text (French)'),
        ),
    ]
