# Generated by Django 5.2.4 on 2025-07-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_remove_review_text_review_text_el_review_text_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AddField(
            model_name='review',
            name='avatar_el',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar (Greek)'),
        ),
        migrations.AddField(
            model_name='review',
            name='avatar_en',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars/', verbose_name='Avatar (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='avatar_es',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar (Spanish)'),
        ),
        migrations.AddField(
            model_name='review',
            name='avatar_fr',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar (French)'),
        ),
        migrations.AddField(
            model_name='review',
            name='name_el',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Greek)'),
        ),
        migrations.AddField(
            model_name='review',
            name='name_en',
            field=models.CharField(default='Misha', max_length=100, verbose_name='Name (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Spanish)'),
        ),
        migrations.AddField(
            model_name='review',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (French)'),
        ),
    ]
