# Generated by Django 5.2.4 on 2025-07-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_remove_review_avatar_remove_review_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description_el',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Greek)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_en',
            field=models.TextField(default='Something', verbose_name='Description (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description (French)'),
        ),
    ]
